name: test get_colab_repos.py

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        python -m pip install python-graphql-client==0.3.0
    - name: print get_colab_repos.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        python get_colab_repos.py
        cat README.md
